config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: "home#show"
  devise_for :users, controllers: { registrations: "registrations" }

  mount Sidekiq::Web => '/sidekiq'

  get "/:username", constraints: UsernameConstraint, controller: "users", action: "show"
  resources :users, only: %i[index show]

  resources :radars do
    resources :blips, controller: "radars/blips", except: :index
  end

  get "/radars/:id/:quadrant", controller: "radars/quadrants", action: "show", as: "radar_quadrant"
  resources :topics, only: %i[show new create]
  resources :bulk_topics, only: %i[new create]
  get "/about", to: "pages#about"

  get "/user/topics", to: "users/topics#index", as: :user_topics

  namespace "api" do
    namespace "v1" do
      resources :radars, only: :show
    end
  end
end

app/models/radar.rb
class Radar < ApplicationRecord
  belongs_to :owner, class_name: "User"
  has_many :blips, dependent: :delete_all

  validates :name,
            presence: true,
            uniqueness: {
              scope: :owner,
              case_sensitive: false
            }
  validates :owner, presence: true
  validates :uuid, presence: true, uniqueness: true

  before_validation :set_uuid, on: :create

  default_scope { order(updated_at: :desc) }

  attr_accessor :topics

  def self.lookup(uuid)
    find_by!(uuid: uuid)
  end

  def self.lookup_for_owner(uuid, owner)
    find_by(uuid: uuid, owner: owner)
  end

  def find_blip(slug)
    blips.joins(:topic).find_by!("topics.slug": slug)
  end

  def owned_by?(user)
    owner == user
  end

  def to_param
    uuid
  end

  def topic?(topic)
    blips.any? do |blip|
      blip.topic == topic
    end
  end

  private

  def set_uuid
    self.uuid = SecureRandom.uuid
  end
end

app/controllers/api/v1/radars_controller.rb
module Api
  module V1
    class RadarsController < ApplicationController
      def show
        @radar = Radar.lookup_for_owner(params[:id], current_user)
        render json: @radar
      end
    end
  end
end

app/controllers/radars/blips_controller.rb
module Radars
  class BlipsController < ApplicationController
    before_action :authenticate_user!, except: :show

    def new
      @blip = radar.blips.new(params[:blip])
      render "new", locals: { quadrants: quadrants, rings: rings, blip: blip, topics: topics }
    end

    def create
      @blip = radar.blips.new(blip_params)
      if @blip.save
        redirect_to radar_quadrant_path(radar, quadrant: blip.quadrant)
      else
        render "new", locals: { quadrants: quadrants, rings: rings, blip: blip, topics: topics }
      end
    end

    def show
      render "show", locals: { quadrants: quadrants, rings: rings, blip: blip } # , topics: topics }
    end

    def edit
      render "edit", locals: { quadrants: quadrants, rings: rings, blip: blip, topics: topics }
    end

    def update
      if blip.update(blip_params)
        redirect_to radar, notice: "Blip updated"
      else
        render "edit", locals: { quadrants: quadrants, rings: rings, blip: blip, topics: topics }
      end
    end

    def destroy
      blip.destroy!
      redirect_to radar_path(radar)
    end

    private

    def blip_params
      params.require(:blip).permit(:topic_id, :quadrant, :ring, :notes)
    end

    def radar
      @radar ||= if current_user
                   current_user.find_radar(uuid: params[:radar_id])
                 else
                   Radar.lookup(params[:radar_id])
                 end
    end

    def blip
      @blip ||= radar.find_blip(params[:id])
    end

    def quadrants
      QuadrantList.new.names_with_values
    end

    def rings
      RingList.new.names_with_values
    end

    def topics
      Topics::Blippable.call(radar).sort_by(&:name)
    end
  end
end

app/controllers/radars/quadrants_controller.rb
module Radars
  class QuadrantsController < ApplicationController
    before_action :authenticate_user!, except: :show

    def show
      @radar = Radar.find_by(uuid: params[:id])
      quadrant = QuadrantList.new.lookup(params[:quadrant])

      render "radars/show", locals: {
        radar: @radar,
        svg: RadarDiagramWithBlips.call(@radar, quadrant)
      }
    end
  end
end

app/controllers/radars_controller.rb
class RadarsController < ApplicationController
  # Prevent Google from repeatedly trying to index old radars
  rescue_from ActiveRecord::RecordNotFound do |_exception|
    render status: :gone
  end

  before_action :authenticate_user!, except: :show

  def index
    render "index", locals: { radars: scoped_radars }
  end

  def show
    radar = find_public_radar
    redirect_to radar_quadrant_path(radar, quadrant: Quadrant.default)
  end

  def new
    render "new", locals: { radar: scoped_radars.new }
  end

  def edit
    radar = find_my_radar
    return redirect_to(new_user_session_path) unless radar
    render "edit", locals: { radar: radar }
  end

  def update
    # :nocov:
    radar = find_my_radar
    if radar.update_attributes(radar_params)
      redirect_to radar
    else
      render "edit", radar: find_my_radar
    end
    # :nocov:
  end

  def create
    radar = current_user.new_radar(radar_params)
    if radar.save
      redirect_to radar
    else
      render "new", locals: { radar: radar }
    end
  end

  def destroy
    radar = find_my_radar
    return redirect_to(new_user_session_path) unless radar
    radar.destroy!
    redirect_to radars_path
  end

  private

  def radar_params
    params.require(:radar).permit(:name, :description, :topics)
  end

  def scoped_radars
    current_user.radars
  end

  def find_my_radar
    current_user.radars.find_by(uuid: params[:id])
  end

  def find_public_radar
    Radar.lookup(params[:id])
  end
end

app/controllers/users/radars_controller.rb
module Users
  class RadarsController < ApplicationController
    def index
      user = User.find_by(username: params[:user_username])
      radars = user.radars
      render 'index', locals: {user: user, radars: radars }
    end
  end
end

app/views/radars/_categorized_blips.html.haml
- RingList.new.each do |ring|
  %h2= ring.name
  - blips_in_scope = radar.blips.in_scope(ring.value, params[:quadrant])
  - if blips_in_scope.any?
    %ul{class: [ring.value, params[:quadrant]]}
      - blips_in_scope.each do |blip|
        %li
          = link_to blip.name, radar_blip_path(radar, blip), id: "blip_#{blip.id}", class: "blip"
          - if blip.notes?
            = icon("comment")
  - else
    No entries

app/views/radars/_form.html.haml
= simple_form_for(radar) do |f|
  = f.input :name
  = f.input :description
  = f.input :topics, as: :text, input_html: { rows: 6 }, hint: "List any new topics that you want track, one per line. You can add more later." unless radar.persisted?
  = f.submit class: 'btn btn-primary'

app/views/radars/_management.html.haml
- if can? :create, radar.blips.new
  = link_to 'New Blip', new_radar_blip_path(radar), class: 'btn btn-primary'
- if can? :delete, radar
  = button_to 'Delete Radar', radar_path(radar), method: :delete, class: 'btn btn-danger',
    data: { confirm: 'Are you sure?' }
- if can? :edit, radar
  = link_to 'Edit Radar', edit_radar_path(radar), class: 'btn btn-default'

app/views/radars/_quadrant_nav.html.haml
%ul.nav.nav-pills
  - QuadrantList.new.quadrants.each do |quadrant|
    %li{class: quadrant.value == params[:quadrant] ? "active" : ""}
      = link_to radar_quadrant_path(@radar, quadrant: quadrant.value) do
        = quadrant.name
        .badge= @radar.blips.in_quadrant(quadrant).count

app/views/radars/_radar.html.haml
.quadrant-nav
  = render 'radars/quadrant_nav'

- if params[:quadrant]
  .row
    .col-md-6
      = render 'radars/categorized_blips', radar: @radar
    .col-md-6
      = raw svg
- else
  Please choose a quadrant to view.

app/views/radars/edit.html.haml
= title 'Edit Radar'

= render 'form', radar: radar

%br
= link_to 'Back to Radar', radar_path(radar), class: 'btn btn-default'

app/views/radars/index.html.haml
= title 'Radars'

- if current_user.first_sign_in?
  %p
    Welcome to <strong>techradar.io</strong>. We have a created a radar to help you get started.

- if radars.any?
  %ul.radars
    - radars.each do |radar|
      %li
        = link_to radar.name, radar
        (
        = pluralize radar.blips.count, "blip"
        )

- else
  No radars

- if can? :create, Radar
  = link_to 'New Radar', new_radar_path, class: 'btn btn-default'

app/views/radars/new.html.haml
= title 'New Radar'

= render 'form', radar: radar

%br
= link_to 'Back to Radars', radars_path, class: 'btn btn-default'

app/views/radars/show.html.haml
.clearfix
  = title radar.name

%p= radar.description if radar.description?

%h3= "Created by #{radar.owner.name}" unless current_user

= render 'radars/management', radar: radar
%br
%br

= render 'radars/radar', radar: radar, svg: svg