config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: "home#show"
  devise_for :users, controllers: { registrations: "registrations" }

  mount Sidekiq::Web => '/sidekiq'

  get "/:username", constraints: UsernameConstraint, controller: "users", action: "show"
  resources :users, only: %i[index show]

  resources :radars do
    resources :blips, controller: "radars/blips", except: :index
  end

  get "/radars/:id/:quadrant", controller: "radars/quadrants", action: "show", as: "radar_quadrant"
  resources :topics, only: %i[show new create]
  resources :bulk_topics, only: %i[new create]
  get "/about", to: "pages#about"

  get "/user/topics", to: "users/topics#index", as: :user_topics

  namespace "api" do
    namespace "v1" do
      resources :radars, only: :show
    end
  end
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{class: "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", type: "button"} &times;
      = content_tag :div, msg, id: "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'techradar.io', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
%li= link_to 'Contact Us', page_path("contact")
- if user_signed_in?
  %li= link_to 'My Radars', radars_path
  %li= link_to 'My Topics', user_topics_path
  %li= link_to 'Account', edit_user_registration_path
  %li= link_to 'Sign Out', destroy_user_session_path, method: 'delete'
  - if current_user.admin?
    %li= link_to 'Users', users_path
- else
  %li= link_to 'Sign In', new_user_session_path
  %li= link_to 'Sign Up', new_user_registration_path

app/views/layouts/application.html.haml
- raise "No title for #{controller_name}/#{action_name}" unless content_for?(:title)
!!!
%html
  %head
    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0"}
    %title= yield(:title) + ' :: techradar.io'
    %link{rel: "stylesheet", href: "https://cdnjs.cloudflare.com/ajax/libs/github-fork-ribbon-css/0.2.0/gh-fork-ribbon.min.css"}
    %meta{name: "description", content: (content_for?(:description) ? yield(:description) : 'Techradar')}
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  - if Rails.env.production?
    :javascript
        !function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","group","track","ready","alias","page","once","off","on"];analytics.factory=function(t){return function(){var e=Array.prototype.slice.call(arguments);e.unshift(t);analytics.push(e);return analytics}};for(var t=0;t<analytics.methods.length;t++){var e=analytics.methods[t];analytics[e]=analytics.factory(e)}analytics.load=function(t){var e=document.createElement("script");e.type="text/javascript";e.async=!0;e.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(e,n)};analytics.SNIPPET_VERSION="3.0.1";
        analytics.load("#{ENV.fetch("SEGMENT_WRITE_KEY")}");
        analytics.page()
        }}();
  %body{class: body_classes}
    %header
      = render 'layouts/navigation'
    %main{role: "main"}
      .container
        = render 'layouts/messages'
        = yield
        .social-links
          Follow
          = link_to "@techradar_io", "https://twitter.com/techradar_io"
          on Twitter
        .disclaimer
          techradar.io is not affiliated with, sponsored or endorsed by
          = link_to "ThoughtWorks", "http://www.thoughtworks.com/"
        .credit
          Built by
          = link_to "@andyw8", "https://twitter.com/andyw8"